# Generated by Django 4.1.7 on 2023-03-07 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('feed_id', models.AutoField(primary_key=True, serialize=False, verbose_name='feed_id')),
                ('photos', models.ImageField(blank=True, upload_to='feed/images', verbose_name='photos')),
                ('location', models.CharField(max_length=50, verbose_name='location')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='time')),
                ('content', models.TextField(verbose_name='content')),
                ('views', models.IntegerField(auto_created=0, verbose_name='views')),
                ('location_name', models.CharField(max_length=50, verbose_name='location name')),
                ('feed_activity', models.ForeignKey(db_column='activity_name', on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='activity.activity')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.user')),
            ],
        ),
    ]
