# Generated by Django 3.2.12 on 2023-03-02 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.CharField(max_length=50, verbose_name='feed id')),
                ('photos', models.ImageField(upload_to=None, verbose_name='photos')),
                ('location', models.CharField(max_length=50, verbose_name='location')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='time')),
                ('content', models.TextField(verbose_name='content')),
                ('views', models.IntegerField(verbose_name='views')),
                ('category', models.CharField(max_length=50, verbose_name='category')),
                ('location_name', models.CharField(max_length=50, verbose_name='location name')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.user')),
            ],
        ),
    ]
