# Generated by Django 4.1.7 on 2023-03-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='name',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='feedname'),
        ),
    ]
