# Generated by Django 4.1.7 on 2023-03-13 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_activity_activity_name'),
        ('user', '0001_initial'),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='feed_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='activity.activity', to_field='activity_name'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.user', to_field='user_id'),
        ),
    ]
