# Generated by Django 4.1.7 on 2023-03-07 09:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=32, unique=True, verbose_name='user id')),
                ('user_password', models.CharField(max_length=128, verbose_name='user password')),
                ('nickname', models.CharField(max_length=20, unique=True, verbose_name='nickname')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('information', models.TextField(blank=True, max_length=200, verbose_name='information')),
                ('profile_image', models.ImageField(blank=True, upload_to='user/images', verbose_name='profile_img')),
                ('like_places', models.TextField(verbose_name='')),
                ('bookmarks', models.CharField(blank=True, max_length=20, unique=True, verbose_name='bookmarks')),
                ('date_birthday', models.DateField(null=True, verbose_name='date birthday')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('gender', models.CharField(choices=[('M', '남성'), ('W', '여성')], max_length=1, verbose_name='성별')),
                ('country', models.CharField(max_length=50, verbose_name='country')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone_number')),
                ('like_activities', models.ManyToManyField(blank=True, db_column='activity_name', related_name='like_activities', to='activity.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='user.user')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='user.user')),
            ],
        ),
    ]
