# Generated by Django 3.2.12 on 2023-03-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='username'),
        ),
    ]
